# Generated by Django 5.2.8 on 2025-12-22 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_purchasebill_purchasebilldetail_purchaseitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseBillDetail',
            new_name='PurchaseBillDetails',
        ),
    ]
